# Generated by Django 3.2.23 on 2023-12-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='proirity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='sr_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
