# Generated by Django 3.2.23 on 2023-12-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20231228_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='proirity',
            new_name='priority',
        ),
    ]
